### ISSUE TITLE
Receive data that is entered through custom tracker (for example the number of cigarettes)

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-issues#20]
Depends on #19 and #61 
- [x] Create an endpoint in the niceday-api to get the number of cigarettes from niceday
- [x] Create a method in the `NicedayClient`
- [x] Create a custom action in rasa for getting the number of cigarettes for a user
- [x] If the user asks 'Hoeveel sigaretten heb ik vandaag gerookt?'. Reply with the number of cigarettes that the user smoked. 'Je hebt vandaag [NUMBER_OF_CIGARETTES] sigaretten gerookt'.

**Comment by svenvanderburg** [comment]
Changes in niceday-api: https://github.com/PerfectFit-project/niceday-components/pull/3
Changes in niceday_client: https://github.com/PerfectFit-project/niceday_client/pull/4

**Comment by svenvanderburg** [comment]
The only thing that's left is the rasa part.
